[package]
name = "display-relay"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
display-relay-core = { path = "../../libs/display-relay-core" }
pollster = "0.4"
tracing.workspace = true
tracing-subscriber.workspace = true
wgpu = "24"
windows-desktop-duplication = { path = "../../platforms/windows-desktop-duplication" }
windows-input = { path = "../../platforms/windows-input" }
winit = "0.30"
